# Generated by Django 6.0.7 on 2026-07-20 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField(blank=True)),
                ("text_entry", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_purchased", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GiftGiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_givers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_note", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="gifts.gift",
                    ),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_assignments",
                        to="gifts.giftgiver",
                    ),
                ),
            ],
            options={
                "ordering": ["giver__name", "gift__sort_order", "gift__id"],
            },
        ),
        migrations.CreateModel(
            name="GiftList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("occasion", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_archived", "event_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="gifts.giftlist",
            ),
        ),
        migrations.CreateModel(
            name="GiftReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_receivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="giftlist",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_lists",
                to="gifts.giftreceiver",
            ),
        ),
        migrations.AddConstraint(
            model_name="giftgiver",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_giver_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="gift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_url__gt", ""),
                    ("text_entry__gt", ""),
                    ("name__gt", ""),
                    _connector="OR",
                ),
                name="gift_requires_url_or_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="gift",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 1), ("priority__lte", 5)),
                name="gift_priority_between_one_and_five",
            ),
        ),
        migrations.AddConstraint(
            model_name="giftreceiver",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_receiver_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="giftlist",
            constraint=models.UniqueConstraint(
                fields=("owner", "receiver", "name"),
                name="unique_list_name_for_owner_receiver",
            ),
        ),
    ]
